<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NewProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [

            // =============================================
            // CHIENS (category_id: 1)
            // =============================================

            // --- Croquettes (subcategory_id: 1) ---
            [
                'category_id' => 1, 'subcategory_id' => 1,
                'name' => 'Purina Pro Plan All Sizes Adult Light Sterilised Poulet 3kg',
                'slug' => 'purina-proplan-all-sizes-adult-light-sterilised-poulet-3kg',
                'description' => 'Croquettes premium pour chiens adultes stérilisés de toutes tailles. Formule légère au poulet pour maintenir le poids idéal.',
                'short_description' => 'Pour chiens adultes stérilisés - Poulet 3kg',
                'price' => 280.00, 'price_old' => 325.00, 'stock' => 30,
                'sku' => 'PP-LIGHT-STERILISED-3KG', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.7, 'review_count' => 78,
                'image' => 'storage/products/07613035123779_C1L1_ProPlanDogALLSIZESADULTLIGHTSTERILISEDChicken3kg_43743769_5d9befbb-1605-4c4e-a33d-57b13bcc4cc6_800x-300x300.webp',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 1,
                'name' => 'Hills Science Plan Chien Adulte',
                'slug' => 'hills-science-plan-chien-adulte',
                'description' => 'Croquettes Hill\'s Science Plan pour chiens adultes. Formule cliniquement prouvée avec antioxydants pour une santé optimale.',
                'short_description' => 'Nutrition scientifiquement prouvée pour chiens',
                'price' => 350.00, 'price_old' => 400.00, 'stock' => 25,
                'sku' => 'HILLS-SP-CHIEN', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 13, 'rating' => 4.8, 'review_count' => 92,
                'image' => 'storage/products/384029_494696_107507_pla_hills_hs_01_8.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 1,
                'name' => 'Royal Canin Giant Adult Bonus Bag',
                'slug' => 'royal-canin-giant-adult-bonus-bag',
                'description' => 'Croquettes Royal Canin spécialement formulées pour les très grandes races (plus de 45kg). Sac bonus grande contenance.',
                'short_description' => 'Nutrition pour chiens de très grandes races',
                'price' => 680.00, 'price_old' => 780.00, 'stock' => 15,
                'sku' => 'RC-GIANT-ADULT-BONUS', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 13, 'rating' => 4.9, 'review_count' => 56,
                'image' => 'storage/products/456900_pla_royal_canin_giant_adult_bonusbag_9.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 1,
                'name' => 'Eukanuba Premium Nutrition Adult Large Giant Breed Poulet 15kg',
                'slug' => 'eukanuba-premium-adult-large-giant-breed-poulet-15kg',
                'description' => 'Croquettes premium Eukanuba pour grandes et très grandes races. Formule au poulet avec DHA pour la santé cérébrale.',
                'short_description' => 'Nutrition premium grandes races - 15kg',
                'price' => 750.00, 'price_old' => 870.00, 'stock' => 12,
                'sku' => 'EUKANUBA-LARGE-15KG', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.8, 'review_count' => 43,
                'image' => 'storage/products/609711_pla_eukanuba_premium_nutrition_adult_large_giant_breed_huhn_15kg_2.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 1,
                'name' => 'Purina Pro Plan Medium Adult Sensitive Skin Optiderma 7kg',
                'slug' => 'purina-proplan-medium-adult-sensitive-skin-optiderma-7kg',
                'description' => 'Croquettes Pro Plan pour chiens moyens à peau sensible. Formule Optiderma riche en oméga 6 pour un pelage sain.',
                'short_description' => 'Peau sensible et pelage brillant - 7kg',
                'price' => 480.00, 'price_old' => 550.00, 'stock' => 22,
                'sku' => 'PP-OPTIDERMA-7KG', 'is_active' => true,
                'discount_percentage' => 13, 'rating' => 4.7, 'review_count' => 67,
                'image' => 'storage/products/99204_pla_purina_proplan_medium_adult_sensitiveskin_optiderma_7kg_hs_01_5.jpg',
            ],

            // --- Accessoires chien (subcategory_id: 3) ---
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Laisse Flexi Classic S Cordon 5m Bleue',
                'slug' => 'laisse-flexi-classic-s-cordon-5m-bleue',
                'description' => 'Laisse rétractable Flexi Classic pour petits chiens jusqu\'à 12kg. Cordon robuste de 5m avec système de freinage et blocage.',
                'short_description' => 'Laisse rétractable 5m pour petits chiens',
                'price' => 95.00, 'price_old' => 115.00, 'stock' => 40,
                'sku' => 'FLEXI-CLASSIC-S-5M', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 17, 'rating' => 4.6, 'review_count' => 134,
                'image' => 'storage/products/flexi_Classic_S_Cord_5m_blue-300x300.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Harnais Confort Réglable Moov Noir',
                'slug' => 'harnais-confort-reglable-moov-noir',
                'description' => 'Harnais confortable et réglable pour chiens. Design ergonomique anti-traction avec 4 points de réglage pour un ajustement parfait.',
                'short_description' => 'Harnais ergonomique anti-traction',
                'price' => 120.00, 'price_old' => 145.00, 'stock' => 35,
                'sku' => 'HARNAIS-MOOV-NOIR-M', 'is_active' => true,
                'discount_percentage' => 17, 'rating' => 4.7, 'review_count' => 89,
                'image' => 'storage/products/harnais-conf-reg-m-moov-noir-300x300.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Gamelle Break Reserve 15L Nordic Sky',
                'slug' => 'gamelle-break-reserve-15l-nordic-sky',
                'description' => 'Distributeur d\'eau Break Reserve 15L Nordic Sky. Réservoir automatique grande capacité pour assurer l\'hydratation continue.',
                'short_description' => 'Distributeur d\'eau automatique 15L',
                'price' => 185.00, 'price_old' => 220.00, 'stock' => 18,
                'sku' => 'BREAK-RESERVE-15L', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 16, 'rating' => 4.5, 'review_count' => 42,
                'image' => 'storage/products/BREAK-RESERVE-15LT-ACQUA-NORDIC-SKY-04206-300x300.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 2,
                'name' => 'Jouet Interactif pour Chien',
                'slug' => 'jouet-interactif-chien',
                'description' => 'Jouet interactif stimulant pour chien. Favorise l\\\'activité mentale et physique.',
                'short_description' => 'Jouet stimulant',
                'price' => 110.00, 'price_old' => 140.00, 'stock' => 67,
                'sku' => 'CHIEN-ACC-004', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 0, 'rating' => 4.3, 'review_count' => 41,
                'image' => 'storage/products/telechargement-2025-05-03T101138.052.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Collier Ajustable Premium',
                'slug' => 'collier-ajustable-premium',
                'description' => 'Collier ajustable de qualité premium. Confortable et résistant.',
                'short_description' => 'Collier premium',
                'price' => 65.00, 'price_old' => 80.00, 'stock' => 73,
                'sku' => 'CHIEN-ACC-005', 'is_active' => true,
                'discount_percentage' => 24, 'rating' => 4.5, 'review_count' => 55,
                'image' => 'storage/products/telechargement.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Coussin Confort pour Chien',
                'slug' => 'coussin-confort-chien',
                'description' => 'Coussin moelleux et confortable pour le repos de votre chien. Déhoussable et lavable.',
                'short_description' => 'Coussin moelleux',
                'price' => 240.00, 'price_old' => 290.00, 'stock' => 34,
                'sku' => 'CHIEN-ACC-006', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 25, 'rating' => 4.7, 'review_count' => 88,
                'image' => 'storage/products/w400 8.jpg',
            ],
            [
                'category_id' => 1, 'subcategory_id' => 3,
                'name' => 'Sac de Transport Confort',
                'slug' => 'sac-transport-confort-chien',
                'description' => 'Sac de transport confortable et sécurisé pour petits chiens. Ventilation optimale.',
                'short_description' => 'Sac de transport',
                'price' => 320.00, 'price_old' => 380.00, 'stock' => 19,
                'sku' => 'CHIEN-ACC-007', 'is_active' => true,
                'is_new' => true, 'is_featured' => true,
                'discount_percentage' => 0, 'rating' => 4.6, 'review_count' => 37,
                'image' => 'storage/products/659193_cbb512588dd044959f8fcba3a2030b23~mv2.avif',
            ],

            // =============================================
            // CHATS (category_id: 2)
            // =============================================

            // --- Cage de transport (subcategory_id: 4) ---
            [
                'category_id' => 2, 'subcategory_id' => 8,
                'name' => 'Cage de Transport Premium',
                'slug' => 'cage-transport-premium-chat',
                'description' => 'Cage de transport robuste et confortable. Ventilation optimale et sécurité renforcée.',
                'short_description' => 'Transport sécurisé',
                'price' => 350.00, 'price_old' => 420.00, 'stock' => 29,
                'sku' => 'CHAT-CAGE-001', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 18, 'rating' => 4.6, 'review_count' => 94,
                'image' => 'storage/products/IMG_20250311_151750-removebg-preview-150x150.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 8,
                'name' => 'Sac de Transport Souple',
                'slug' => 'sac-transport-souple-chat',
                'description' => 'Sac de transport souple et confortable. Idéal pour les déplacements courts.',
                'short_description' => 'Transport souple',
                'price' => 190.00, 'price_old' => 240.00, 'stock' => 41,
                'sku' => 'CHAT-CAGE-002', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 19, 'rating' => 4.5, 'review_count' => 67,
                'image' => 'storage/products/New-Project-7-1-150x150.webp',
            ],

            // --- Croquettes pour chat (subcategory_id: 5) ---
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Hills Prescription Diet i/d Digestive Care Poulet 3kg',
                'slug' => 'hills-prescription-diet-id-digestive-care-poulet-3kg',
                'description' => 'Aliment diététique complet pour chats adultes - Aide à la récupération gastro-intestinale. Riche en électrolytes et haute digestibilité.',
                'short_description' => 'Nutrition thérapeutique digestive pour chats',
                'price' => 430.00, 'price_old' => 480.00, 'stock' => 20,
                'sku' => 'HILLS-ID-CAT-3KG', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 10, 'rating' => 4.8, 'review_count' => 45,
                'image' => 'storage/products/242425_pla_hills_prescriptiondiet_id_digestivecare_katzenfutter_huhn_3kg_hs_01_6.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Hills Prescription Diet z/d Food Sensitivities Chat',
                'slug' => 'hills-prescription-diet-zd-food-sensitivities-chat',
                'description' => 'Aliment diététique pour chats souffrant d\'allergies et intolérances alimentaires. Protéines hautement hydrolysées.',
                'short_description' => 'Spécial allergies et intolérances alimentaires',
                'price' => 450.00, 'price_old' => 510.00, 'stock' => 15,
                'sku' => 'HILLS-ZD-CAT', 'is_active' => true,
                'discount_percentage' => 12, 'rating' => 4.7, 'review_count' => 32,
                'image' => 'storage/products/242430_242431_pla_hills_prescriptiondiet_zd_food_sensitivities_katzenfutter_original_hs_01_1.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Hills Prescription Diet Metabolic Weight Management Chat',
                'slug' => 'hills-prescription-diet-metabolic-weight-management-chat',
                'description' => 'Aliment cliniquement prouvé pour aider les chats à perdre et maintenir leur poids idéal. Formule enrichie en L-carnitine.',
                'short_description' => 'Contrôle du poids cliniquement prouvé',
                'price' => 420.00, 'price_old' => 470.00, 'stock' => 18,
                'sku' => 'HILLS-METABOLIC-CAT', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 11, 'rating' => 4.9, 'review_count' => 67,
                'image' => 'storage/products/64126_243997_70882_243996_pla_hills_prescriptiondiet_metabolic_felineweight_management_huhn_hs_02_3.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Royal Canin Fussy Cat',
                'slug' => 'royal-canin-fussy-cat',
                'description' => 'Croquettes spécialement formulées pour les chats difficiles. Texture et forme unique qui stimulent l\'appétit des chats capricieux.',
                'short_description' => 'Pour chats difficiles et capricieux',
                'price' => 185.00, 'price_old' => 210.00, 'stock' => 40,
                'sku' => 'RC-FUSSY-CAT', 'is_active' => true,
                'discount_percentage' => 12, 'rating' => 4.6, 'review_count' => 89,
                'image' => 'storage/products/610398_610211_610214_610216_610399_pla_royal_canin_fussy_cat_1000x1000_hs_01_0.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Royal Canin Urinary Care Chat',
                'slug' => 'royal-canin-urinary-care-chat',
                'description' => 'Croquettes pour chat adulte favorisant la santé urinaire. Aide à maintenir un pH urinaire équilibré et dilue les urines.',
                'short_description' => 'Santé urinaire optimale pour chat adulte',
                'price' => 195.00, 'price_old' => 225.00, 'stock' => 35,
                'sku' => 'RC-URINARY-CAT', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 13, 'rating' => 4.7, 'review_count' => 112,
                'image' => 'storage/products/rc_vet_dry_caturinarysomc_mv_eretailkit_de_de_7.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Purina Pro Plan Delicate Dinde Chat',
                'slug' => 'purina-proplan-delicate-dinde-chat',
                'description' => 'Croquettes premium pour chats adultes à l\'estomac sensible. Formule à base de dinde avec prébiotiques pour une meilleure digestion.',
                'short_description' => 'Formule douce pour estomacs sensibles',
                'price' => 220.00, 'price_old' => 255.00, 'stock' => 30,
                'sku' => 'PP-DELICATE-DINDE', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.6, 'review_count' => 78,
                'image' => 'storage/products/84311_pla_purina_proplan_delicate_reichtruthahn_hs_01_8.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Croquettes Reflex Chat',
                'slug' => 'croquettes-reflex-chat',
                'description' => 'Croquettes complètes et équilibrées pour chats adultes. Formule riche en protéines animales avec taurine pour la santé cardiaque.',
                'short_description' => 'Nutrition complète pour chats adultes',
                'price' => 120.00, 'price_old' => 145.00, 'stock' => 60,
                'sku' => 'REFLEX-CAT-2KG', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 17, 'rating' => 4.5, 'review_count' => 134,
                'image' => 'storage/products/Croquettes Reflex Chat.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Croquettes pour chat Reflex',
                'slug' => 'croquettes-pour-chat-reflex',
                'description' => 'Aliment complet pour chats adultes. Enrichi en oméga 3 et 6 pour un pelage brillant et une peau saine.',
                'short_description' => 'Pelage brillant et peau saine',
                'price' => 105.00, 'price_old' => null, 'stock' => 55,
                'sku' => 'REFLEX-CAT-STD', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 67,
                'image' => 'storage/products/Croquettes pour chat - Reflex.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Nourriture pour chaton REFLEX PLUS',
                'slug' => 'nourriture-pour-chaton-reflex-plus',
                'description' => 'Croquettes premium spécialement formulées pour les chatons de 0 à 12 mois. Riche en DHA pour le développement cérébral.',
                'short_description' => 'Formule premium pour la croissance des chatons',
                'price' => 170.00, 'price_old' => 200.00, 'stock' => 45,
                'sku' => 'REFLEX-PLUS-KITTEN', 'is_active' => true,
                'discount_percentage' => 15, 'rating' => 4.7, 'review_count' => 56,
                'image' => 'storage/products/Nourriture pour chaton - REFLEX PLUS.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Cat+ Premium jaune',
                'slug' => 'cat-premium-jaune',
                'description' => 'Croquettes premium pour chats adultes - gamme jaune. Formule riche en protéines et vitamines essentielles.',
                'short_description' => 'Gamme premium pour chats adultes',
                'price' => 95.00, 'price_old' => 110.00, 'stock' => 50,
                'sku' => 'CAT-PLUS-JAUNE', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.4, 'review_count' => 43,
                'image' => 'storage/products/cat + premium jaune.png',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Cat+ Premium rouge',
                'slug' => 'cat-premium-rouge',
                'description' => 'Croquettes premium pour chats adultes - gamme rouge. Formule au bœuf riche en protéines pour une vitalité optimale.',
                'short_description' => 'Formule au bœuf pour chats adultes',
                'price' => 95.00, 'price_old' => 110.00, 'stock' => 50,
                'sku' => 'CAT-PLUS-ROUGE', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.5, 'review_count' => 38,
                'image' => 'storage/products/cat + premium rouge.png',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Frendi wet cat food with beef chunks 400g',
                'slug' => 'frendi-wet-cat-food-beef-chunks-400g',
                'description' => 'Nourriture humide pour chats adultes aux morceaux de bœuf en gelée. Haute teneur en eau pour l\'hydratation.',
                'short_description' => 'Pâtée aux morceaux de bœuf 400g',
                'price' => 18.00, 'price_old' => 22.00, 'stock' => 100,
                'sku' => 'FRENDI-BEEF-400G', 'is_active' => true,
                'discount_percentage' => 18, 'rating' => 4.3, 'review_count' => 65,
                'image' => 'storage/products/Frendi wet cat food with beef chunks 400 g.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Frendi wet cat food with chicken chunks 400g',
                'slug' => 'frendi-wet-cat-food-chicken-chunks-400g',
                'description' => 'Nourriture humide pour chats adultes aux morceaux de poulet en gelée. Appétissante et riche en protéines.',
                'short_description' => 'Pâtée aux morceaux de poulet 400g',
                'price' => 18.00, 'price_old' => 22.00, 'stock' => 100,
                'sku' => 'FRENDI-CHICKEN-400G', 'is_active' => true,
                'discount_percentage' => 18, 'rating' => 4.4, 'review_count' => 72,
                'image' => 'storage/products/Frendi wet cat food with chicken chunks 400 g.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Purina Felix Fantastic bleu',
                'slug' => 'purina-felix-fantastic-bleu',
                'description' => 'Sachets fraîcheur Felix Fantastic 4x85g. Délicieuses bouchées en gelée pour chat adulte. Variété poisson.',
                'short_description' => 'Sachets fraîcheur Felix 4x85g - Poisson',
                'price' => 28.00, 'price_old' => 35.00, 'stock' => 120,
                'sku' => 'FELIX-FANTASTIC-BLEU', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 20, 'rating' => 4.6, 'review_count' => 203,
                'image' => 'storage/products/Purina Felix Fantastic bleu.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Purina Felix Fantastic rouge',
                'slug' => 'purina-felix-fantastic-rouge',
                'description' => 'Sachets fraîcheur Felix Fantastic 4x85g. Délicieuses bouchées en gelée pour chat adulte. Variété bœuf et poulet.',
                'short_description' => 'Sachets fraîcheur Felix 4x85g - Bœuf & Poulet',
                'price' => 28.00, 'price_old' => 35.00, 'stock' => 120,
                'sku' => 'FELIX-FANTASTIC-ROUGE', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 20, 'rating' => 4.7, 'review_count' => 187,
                'image' => 'storage/products/Purina Felix Fantastic rouge.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Purina Felix Duo',
                'slug' => 'purina-felix-duo',
                'description' => 'Multipack Felix Duo - mélange de 2 saveurs en gelée pour varier les plaisirs de votre chat. Format économique.',
                'short_description' => 'Multipack duo saveurs pour chat',
                'price' => 55.00, 'price_old' => 68.00, 'stock' => 80,
                'sku' => 'FELIX-DUO', 'is_active' => true,
                'discount_percentage' => 19, 'rating' => 4.5, 'review_count' => 145,
                'image' => 'storage/products/Purina Felix Felix Duo.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Pâté Plaisir Bœuf pour chats 100g',
                'slug' => 'pate-plaisir-boeuf-pour-chats-100g',
                'description' => 'Pâté appétissant au bœuf pour chats adultes. Préparation naturelle sans colorants artificiels, riche en protéines.',
                'short_description' => 'Pâté naturel au bœuf 100g',
                'price' => 12.00, 'price_old' => null, 'stock' => 150,
                'sku' => 'PLAISIR-BOEUF-100G', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 88,
                'image' => 'storage/products/Pâté Plaisir Bœuf pour chats 100g.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Pâté Plaisir Kitten pour chatons au poulet',
                'slug' => 'pate-plaisir-kitten-pour-chatons-au-poulet',
                'description' => 'Pâté spécial chatons au poulet. Formule douce et nutritive adaptée aux besoins des jeunes chats jusqu\'à 12 mois.',
                'short_description' => 'Pâté au poulet pour chatons',
                'price' => 14.00, 'price_old' => null, 'stock' => 120,
                'sku' => 'PLAISIR-KITTEN-POULET', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 0, 'rating' => 4.6, 'review_count' => 54,
                'image' => 'storage/products/Pâté Plaisir Kitten pour chatons au poulet.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Pâté Plaisir Kitten pour chatons au saumon',
                'slug' => 'pate-plaisir-kitten-pour-chatons-au-saumon',
                'description' => 'Pâté spécial chatons au saumon. Riche en oméga 3 pour le développement cérébral et oculaire des jeunes chats.',
                'short_description' => 'Pâté au saumon pour chatons',
                'price' => 14.00, 'price_old' => null, 'stock' => 100,
                'sku' => 'PLAISIR-KITTEN-SAUMON', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.5, 'review_count' => 41,
                'image' => 'storage/products/Pâté Plaisir Kitten pour chatons au salmon.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Plaisir Sachets fraîcheur pour Chaton 100g bleu',
                'slug' => 'plaisir-sachets-fraicheur-chaton-100g-bleu',
                'description' => 'Sachets fraîcheur pour chatons - variété bleue (poisson). Préparation douce et savoureuse adaptée aux chatons.',
                'short_description' => 'Sachets fraîcheur chaton - Poisson 100g',
                'price' => 10.00, 'price_old' => 13.00, 'stock' => 130,
                'sku' => 'PLAISIR-SACHET-KITTEN-BLEU', 'is_active' => true,
                'discount_percentage' => 23, 'rating' => 4.4, 'review_count' => 61,
                'image' => 'storage/products/Plaisir Sachets fraîcheur pour Chaton 100g bleu.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Plaisir Sachets fraîcheur pour Chaton 100g orange',
                'slug' => 'plaisir-sachets-fraicheur-chaton-100g-orange',
                'description' => 'Sachets fraîcheur pour chatons - variété orange (poulet & carotte). Recette naturelle pour chatons en pleine croissance.',
                'short_description' => 'Sachets fraîcheur chaton - Poulet 100g',
                'price' => 10.00, 'price_old' => 13.00, 'stock' => 130,
                'sku' => 'PLAISIR-SACHET-KITTEN-ORANGE', 'is_active' => true,
                'discount_percentage' => 23, 'rating' => 4.3, 'review_count' => 47,
                'image' => 'storage/products/Plaisir Sachets fraîcheur pour Chaton 100g orange.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Plaisir Sachets fraîcheur pour Chaton 100g rouge',
                'slug' => 'plaisir-sachets-fraicheur-chaton-100g-rouge',
                'description' => 'Sachets fraîcheur pour chatons - variété rouge (bœuf & légumes). Formule complète pour la santé des jeunes chats.',
                'short_description' => 'Sachets fraîcheur chaton - Bœuf 100g',
                'price' => 10.00, 'price_old' => 13.00, 'stock' => 130,
                'sku' => 'PLAISIR-SACHET-KITTEN-ROUGE', 'is_active' => true,
                'discount_percentage' => 23, 'rating' => 4.4, 'review_count' => 52,
                'image' => 'storage/products/Plaisir Sachets fraîcheur pour Chaton 100g rouge.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Tomy Chat 415g Boeuf',
                'slug' => 'tomy-chat-415g-boeuf',
                'description' => 'Pâtée Tomy pour chats adultes aux morceaux de bœuf en sauce. Grande boîte économique de 415g.',
                'short_description' => 'Grande pâtée au bœuf 415g',
                'price' => 22.00, 'price_old' => 28.00, 'stock' => 90,
                'sku' => 'TOMY-BOEUF-415G', 'is_active' => true,
                'discount_percentage' => 21, 'rating' => 4.2, 'review_count' => 74,
                'image' => 'storage/products/Tomy Chat 415g Boeuf.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Chunks with fish in natural gravy WishCat',
                'slug' => 'chunks-fish-natural-gravy-wishcat',
                'description' => 'Bouchées de poisson en sauce naturelle WishCat pour chats adultes. Sans conservateurs artificiels, 100% naturel.',
                'short_description' => 'Bouchées poisson en sauce naturelle',
                'price' => 16.00, 'price_old' => null, 'stock' => 80,
                'sku' => 'WISHCAT-FISH-GRAVY', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.5, 'review_count' => 39,
                'image' => 'storage/products/chunks with fish in natural gravy wishcat.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Morceaux de poisson Cat+',
                'slug' => 'morceaux-de-poisson-cat-plus',
                'description' => 'Nourriture humide Cat+ aux morceaux de poisson pour chats adultes. Formule complète et appétissante.',
                'short_description' => 'Morceaux de poisson pour chats adultes',
                'price' => 15.00, 'price_old' => null, 'stock' => 95,
                'sku' => 'CAT-PLUS-POISSON', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.3, 'review_count' => 28,
                'image' => 'storage/products/morceaux de poisson cat+.png',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 5,
                'name' => 'Croquettes Premium Chat Adulte',
                'slug' => 'croquettes-premium-chat-adulte',
                'description' => 'Croquettes premium pour chats adultes. Nutrition complète et équilibrée.',
                'short_description' => 'Premium chat adulte',
                'price' => 125.00, 'price_old' => 150.00, 'stock' => 55,
                'sku' => 'CHAT-CRO-007', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.5, 'review_count' => 64,
                'image' => 'storage/products/w400.jpg',
            ],

            // --- Litière & Accessoires chat (subcategory_id: 6) ---
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Cat Boom Strong Clumping Bentonite Cat Litter Jasmin',
                'slug' => 'cat-boom-strong-clumping-bentonite-cat-litter-jasmin',
                'description' => 'Litière agglomérante en bentonite à la senteur jasmin. Absorption ultra-rapide et contrôle des odeurs pendant 30 jours.',
                'short_description' => 'Litière bentonite parfum jasmin - Agglomérante',
                'price' => 75.00, 'price_old' => 90.00, 'stock' => 70,
                'sku' => 'CATBOOM-JASMIN', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 17, 'rating' => 4.6, 'review_count' => 118,
                'image' => 'storage/products/Cat Boom Strong Clumping Bentonite Cat Litter Jasmin.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Cat Litter Pure Life bleu',
                'slug' => 'cat-litter-pure-life-bleu',
                'description' => 'Litière Pure Life bleu - parfum frais et apaisant. Formule agglomérante haute performance pour un nettoyage facile.',
                'short_description' => 'Litière agglomérante Pure Life - Parfum frais',
                'price' => 65.00, 'price_old' => 78.00, 'stock' => 85,
                'sku' => 'PURELIFE-BLEU', 'is_active' => true,
                'discount_percentage' => 17, 'rating' => 4.5, 'review_count' => 92,
                'image' => 'storage/products/Cat Litter Pure Life  bleu.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Cat Litter Pure Life rose',
                'slug' => 'cat-litter-pure-life-rose',
                'description' => 'Litière Pure Life rose - senteur florale délicate. Absorption maximale avec moins de poussière pour le confort de votre chat.',
                'short_description' => 'Litière agglomérante Pure Life - Senteur florale',
                'price' => 65.00, 'price_old' => 78.00, 'stock' => 85,
                'sku' => 'PURELIFE-ROSE', 'is_active' => true,
                'discount_percentage' => 17, 'rating' => 4.5, 'review_count' => 88,
                'image' => 'storage/products/Cat Litter Pure Life rose.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Proline Cat Litter Lavande Babypowder',
                'slug' => 'proline-cat-litter-lavande-babypowder',
                'description' => 'Litière Proline à double parfum lavande et talc bébé. Agglomérante, faible en poussière et longue durée d\'utilisation.',
                'short_description' => 'Litière double parfum lavande & talc',
                'price' => 70.00, 'price_old' => 85.00, 'stock' => 65,
                'sku' => 'PROLINE-LAVANDE', 'is_active' => true,
                'discount_percentage' => 18, 'rating' => 4.6, 'review_count' => 107,
                'image' => 'storage/products/Proline Cat Litter Lavande babybowder.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 7,
                'name' => 'Tiaki Scratching Stairs Puzzle',
                'slug' => 'tiaki-scratching-stairs-puzzle',
                'description' => 'Escalier griffoir puzzle Tiaki - combinaison intelligente de griffoir et jeu d\'éveil. Structure en carton résistant.',
                'short_description' => 'Griffoir escalier et jeu d\'éveil',
                'price' => 145.00, 'price_old' => 175.00, 'stock' => 25,
                'sku' => 'TIAKI-SCRATCH-STAIRS', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 17, 'rating' => 4.7, 'review_count' => 34,
                'image' => 'storage/products/527097_pla_tiaki_scratching_stairs_puzzle_fg_6858_3.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 7,
                'name' => 'Arbre à Chat Cat Flower',
                'slug' => 'arbre-a-chat-cat-flower',
                'description' => 'Arbre à chat design fleur avec griffoirs, tunnels et plateformes. Structure ultra-stable en peluche douce.',
                'short_description' => 'Arbre à chat design fleur multi-niveaux',
                'price' => 320.00, 'price_old' => 390.00, 'stock' => 12,
                'sku' => 'CAT-FLOWER-TREE', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 18, 'rating' => 4.8, 'review_count' => 47,
                'image' => 'storage/products/63085_PLA_Kratzbaum_Cat_Flower_1_6.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 7,
                'name' => 'Foldable Tower Chat',
                'slug' => 'foldable-tower-chat',
                'description' => 'Tour pliable pour chat avec différents niveaux de jeu. Facile à ranger et à transporter. Idéal pour les petits espaces.',
                'short_description' => 'Tour de jeu pliable pour chat',
                'price' => 185.00, 'price_old' => 220.00, 'stock' => 20,
                'sku' => 'FOLDABLE-TOWER-CAT', 'is_active' => true,
                'discount_percentage' => 16, 'rating' => 4.5, 'review_count' => 29,
                'image' => 'storage/products/75300_foldable_tower_fg_3805_7.jpg',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 8,
                'name' => 'Fontaine à Eau pour Chat',
                'slug' => 'fontaine-eau-chat',
                'description' => 'Fontaine à eau automatique. Encourage l\\\'hydratation de votre chat.',
                'short_description' => 'Fontaine automatique',
                'price' => 240.00, 'price_old' => 290.00, 'stock' => 34,
                'sku' => 'CHAT-ACC-004', 'is_active' => true,
                'is_new' => true, 'is_bestseller' => true,
                'discount_percentage' => 0, 'rating' => 4.8, 'review_count' => 126,
                'image' => 'storage/products/28e1c5be-fbda-4056-bb29-2cb5fe00f7ee-700x700.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 8,
                'name' => 'Jouet Interactif Petiz',
                'slug' => 'jouet-interactif-petiz',
                'description' => 'Jouet interactif électronique pour chat. Stimule l\\\'instinct de chasse.',
                'short_description' => 'Jouet électronique',
                'price' => 130.00, 'price_old' => 160.00, 'stock' => 46,
                'sku' => 'CHAT-ACC-005', 'is_active' => true,
                'discount_percentage' => 17, 'rating' => 4.5, 'review_count' => 81,
                'image' => 'storage/products/Products-Image-Petiz-55-700x700.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Litière Autonettoyante',
                'slug' => 'litiere-autonettoyante',
                'description' => 'Litière autonettoyante moderne. Hygiène optimale et facilité d\\\'utilisation.',
                'short_description' => 'Litière automatique',
                'price' => 1800.00, 'price_old' => 2200.00, 'stock' => 12,
                'sku' => 'CHAT-ACC-006', 'is_active' => true,
                'is_new' => true, 'is_bestseller' => true, 'is_featured' => true,
                'discount_percentage' => 17, 'rating' => 4.9, 'review_count' => 167,
                'image' => 'storage/products/8003507986428-1_368x368_crop_center.webp',
            ],
            [
                'category_id' => 2, 'subcategory_id' => 6,
                'name' => 'Bac à Litière Design',
                'slug' => 'bac-litiere-design',
                'description' => 'Bac à litière au design moderne. Facile à nettoyer avec filtre anti-odeurs.',
                'short_description' => 'Bac litière moderne',
                'price' => 140.00, 'price_old' => 170.00, 'stock' => 38,
                'sku' => 'CHAT-ACC-007', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 52,
                'image' => 'storage/products/jlsb.jpg',
            ],

            // =============================================
            // OISEAUX (category_id: 3)
            // =============================================

            // --- Cages & Volières (subcategory_id: 9) ---
            [
                'category_id' => 3, 'subcategory_id' => 9,
                'name' => 'Cage Elevage Zolux Primo Cati 671',
                'slug' => 'cage-elevage-zolux-primo-cati-671',
                'description' => 'Cage d\'élevage Zolux Primo Cati pour oiseaux. Grande ouverture, mangeoires et abreuvoirs inclus. Facile à nettoyer.',
                'short_description' => 'Cage d\'élevage spacieuse pour oiseaux',
                'price' => 280.00, 'price_old' => 320.00, 'stock' => 15,
                'sku' => 'ZOLUX-CATI-671', 'is_active' => true,
                'discount_percentage' => 13, 'rating' => 4.6, 'review_count' => 38,
                'image' => 'storage/products/Cage-delevage-Zolux-Primo-cati-671-300x300 (1).jpg',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 9,
                'name' => 'Cage Perroquet VL422174',
                'slug' => 'cage-perroquet-vl422174',
                'description' => 'Grande cage pour perroquets avec barreaux robustes et espacés. Multiples portes d\'accès et équipements inclus.',
                'short_description' => 'Grande cage solide pour perroquets',
                'price' => 450.00, 'price_old' => 520.00, 'stock' => 8,
                'sku' => 'CAGE-VL422174', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 13, 'rating' => 4.7, 'review_count' => 24,
                'image' => 'storage/products/VL422174-e1737985565383-700x779.webp',
            ],

            // --- Graines & Nutrition (subcategory_id: 10) ---
            [
                'category_id' => 3, 'subcategory_id' => 10,
                'name' => 'Mélange pour Calopsitte',
                'slug' => 'melange-pour-calopsitte',
                'description' => 'Mélange de graines spécialement formulé pour les calopsittes. Riche en millet, avoine et graines de tournesol.',
                'short_description' => 'Mélange de graines pour calopsittes',
                'price' => 45.00, 'price_old' => null, 'stock' => 50,
                'sku' => 'SEED-CALOPSITTE', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.7, 'review_count' => 63,
                'image' => 'storage/products/Melange-pour-calopsitte-e1714228585714-510x510-1.webp',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 10,
                'name' => 'Mélange pour Canaries avec Alpiste',
                'slug' => 'melange-pour-canaries-avec-alpiste',
                'description' => 'Mélange riche en alpiste pour canaries chanteurs. Composition équilibrée pour maintenir la forme vocale et physique.',
                'short_description' => 'Mélange avec alpiste pour canaries chanteurs',
                'price' => 38.00, 'price_old' => null, 'stock' => 65,
                'sku' => 'SEED-CANARY-ALPISTE', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 0, 'rating' => 4.8, 'review_count' => 95,
                'image' => 'storage/products/Melange-pour-canaries-avec-alpiste-e1714147138859-510x510-1.webp',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 10,
                'name' => 'Aliment pour Perroquet',
                'slug' => 'aliment-pour-perroquet',
                'description' => 'Mélange premium de fruits secs, graines et granulés pour perroquets. Formule complète enrichie en vitamines A, D3 et E.',
                'short_description' => 'Nutrition complète pour perroquets',
                'price' => 65.00, 'price_old' => 78.00, 'stock' => 40,
                'sku' => 'ALIMENT-PERROQUET', 'is_active' => true,
                'discount_percentage' => 17, 'rating' => 4.6, 'review_count' => 47,
                'image' => 'storage/products/Aliment-pour-perroquet-510x510-1.webp',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 10,
                'name' => 'Graines Premium Mix',
                'slug' => 'graines-premium-mix-oiseaux',
                'description' => 'Mélange premium de graines variées. Pour tous types d\'oiseaux.',
                'short_description' => 'Mix premium',
                'price' => 55.00, 'price_old' => 68.00, 'stock' => 51,
                'sku' => 'OISEAU-GRAIN-004', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.5, 'review_count' => 64,
                'image' => 'storage/products/575434__53870-700x700.webp',
            ],

            // --- Accessoires (subcategory_id: 11) ---
            [
                'category_id' => 3, 'subcategory_id' => 11,
                'name' => 'HidraPlus 1kg Avianvet - Électrolytes oiseaux',
                'slug' => 'hidraplus-1kg-avianvet-electrolytes-oiseaux',
                'description' => 'Complément à base d\'électrolytes à dissoudre dans l\'eau pour oiseaux. Prévient la déshydratation lors de stress ou de chaleur.',
                'short_description' => 'Complément électrolytes pour oiseaux',
                'price' => 180.00, 'price_old' => 210.00, 'stock' => 20,
                'sku' => 'HIDRAPLUS-1KG', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 14, 'rating' => 4.9, 'review_count' => 31,
                'image' => 'storage/products/hidraplus-1kg-avianvet-1825-eur-26251-avianvet-hidraplus-avianvet-est-un-complement-a-base-delectrolytes-a-dissoudre-dans-leau-o.jpg',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 11,
                'name' => 'Abreuvoir oiseaux',
                'slug' => 'abreuvoir-oiseaux',
                'description' => 'Abreuvoir pratique pour oiseaux en cage. Facile à fixer et à nettoyer, capacité adaptée aux petits et moyens oiseaux.',
                'short_description' => 'Abreuvoir facile à fixer pour oiseaux',
                'price' => 25.00, 'price_old' => null, 'stock' => 80,
                'sku' => 'ABREUVOIR-OISEAUX', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 56,
                'image' => 'storage/products/Abreuvoir-oiseaux-510x510-1.webp',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 11,
                'name' => 'Perchoir Naturel',
                'slug' => 'perchoir-naturel-oiseaux',
                'description' => 'Perchoir en bois naturel. Favorise le bien-être et l\'exercice des pattes.',
                'short_description' => 'Perchoir bois',
                'price' => 45.00, 'price_old' => 55.00, 'stock' => 82,
                'sku' => 'OISEAU-ACC-003', 'is_active' => true,
                'discount_percentage' => 22, 'rating' => 4.3, 'review_count' => 38,
                'image' => 'storage/products/045671b0f8370fb4e7f6f50230430e5285a325d2_33b04a0f1aa325976f5c117aee20eb1053e3f3de.webp',
            ],
            [
                'category_id' => 3, 'subcategory_id' => 11,
                'name' => 'Jouet Suspendu en Bois pour Oiseau',
                'slug' => 'jouet-suspendu-en-bois-pour-oiseau',
                'description' => 'Jouet suspendu en bois naturel pour oiseaux. Idéal pour stimuler l\'exercice, le jeu et le bien-être de votre oiseau en cage. Facile à suspendre avec son crochet métallique.',
                'short_description' => 'Jouet en bois naturel pour divertir vos oiseaux',
                'price' => 45.00, 'price_old' => 60.00, 'stock' => 40,
                'sku' => 'OISEAU-TOY-WOOD', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 25, 'rating' => 4.6, 'review_count' => 34,
                'image' => 'storage/products/61i5pYks9dL._AC_UF1000,1000_QL80_.jpg',
            ],

            // =============================================
            // POISSONS (category_id: 4)
            // =============================================

            // --- Aquariums (subcategory_id: 12) ---
            [
                'category_id' => 4, 'subcategory_id' => 12,
                'name' => 'EHEIM Vivaline LED Aquarium',
                'slug' => 'eheim-vivaline-led-aquarium',
                'description' => 'Aquarium EHEIM Vivaline avec éclairage LED intégré. Design élégant avec filtre interne silencieux et couvercle. Kit complet.',
                'short_description' => 'Aquarium LED complet avec filtre silencieux',
                'price' => 850.00, 'price_old' => 980.00, 'stock' => 8,
                'sku' => 'EHEIM-VIVALINE-LED', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 13, 'rating' => 4.9, 'review_count' => 34,
                'image' => 'storage/products/EHEIM-vivalineLED-126--300x300.jpg',
            ],
            [
                'category_id' => 4, 'subcategory_id' => 12,
                'name' => 'Aquarium Débutant Complet',
                'slug' => 'aquarium-debutant-complet',
                'description' => 'Kit aquarium complet pour débutants. Tout le nécessaire pour démarrer.',
                'short_description' => 'Kit débutant',
                'price' => 650.00, 'price_old' => 780.00, 'stock' => 24,
                'sku' => 'POISSON-AQU-002', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 20, 'rating' => 4.6, 'review_count' => 87,
                'image' => 'storage/products/401438-300x300.jpg',
            ],
            [
                'category_id' => 4, 'subcategory_id' => 12,
                'name' => 'Nano Aquarium Design',
                'slug' => 'nano-aquarium-design',
                'description' => 'Nano aquarium au design épuré. Parfait pour petits espaces.',
                'short_description' => 'Nano aquarium',
                'price' => 850.00, 'price_old' => 990.00, 'stock' => 31,
                'sku' => 'POISSON-AQU-003', 'is_active' => true,
                'is_new' => true, 'is_featured' => true,
                'discount_percentage' => 15, 'rating' => 4.7, 'review_count' => 96,
                'image' => 'storage/products/789e13160e60e4f591114fc3149abb7e5259aac8_9f6d373777204c04c4b83b37e56d1eabc5aa59d1.webp',
            ],

            // --- Nourriture poissons (subcategory_id: 13) ---
            [
                'category_id' => 4, 'subcategory_id' => 13,
                'name' => 'Basic Tropical Flakes Dajana',
                'slug' => 'basic-tropical-flakes-dajana',
                'description' => 'Flocons de base Dajana pour poissons tropicaux. Formule équilibrée enrichie en spiruline et vitamines pour des couleurs éclatantes.',
                'short_description' => 'Flocons nutritifs pour poissons tropicaux',
                'price' => 55.00, 'price_old' => 70.00, 'stock' => 60,
                'sku' => 'DAJANA-TROPICAL-FLAKES', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 21, 'rating' => 4.6, 'review_count' => 87,
                'image' => 'storage/products/basic-tropical-flakes-dajana1-300x300.jpg',
            ],
            [
                'category_id' => 4, 'subcategory_id' => 13,
                'name' => 'Sera KOI Royal 5 Nourriture Koïs',
                'slug' => 'sera-koi-royal-5-nourriture-kois',
                'description' => 'Nourriture premium Sera KOI Royal pour carpes koïs. Granulés flottants enrichis en spiruline pour des couleurs vives.',
                'short_description' => 'Granulés flottants premium pour carpes koïs',
                'price' => 130.00, 'price_old' => 155.00, 'stock' => 25,
                'sku' => 'SERA-KOI-ROYAL-5', 'is_active' => true,
                'discount_percentage' => 16, 'rating' => 4.7, 'review_count' => 43,
                'image' => 'storage/products/sera-KOI-ROYAL-5-65-300x300.jpg',
            ],
            [
                'category_id' => 4, 'subcategory_id' => 13,
                'name' => 'Granulés Poissons Tropicaux',
                'slug' => 'granules-poissons-tropicaux',
                'description' => 'Granulés nutritifs pour poissons tropicaux. Haute digestibilité.',
                'short_description' => 'Granulés tropicaux',
                'price' => 48.00, 'price_old' => 60.00, 'stock' => 54,
                'sku' => 'POISSON-NOUR-003', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.6, 'review_count' => 58,
                'image' => 'storage/products/178538_PHO_PRO_CLIP_8853-1.jpg',
            ],

            // --- Accessoires aquarium (subcategory_id: 14) ---
            [
                'category_id' => 4, 'subcategory_id' => 14,
                'name' => 'Éponge pour Aquarium Trixie',
                'slug' => 'eponge-pour-aquarium-trixie',
                'description' => 'Éponge de nettoyage Trixie pour aquarium. Nettoyage efficace des vitres sans rayures. Compatible avec tous les aquariums.',
                'short_description' => 'Éponge nettoyante sans rayures pour aquarium',
                'price' => 22.00, 'price_old' => null, 'stock' => 90,
                'sku' => 'TRIXIE-EPONGE-AQU', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 58,
                'image' => 'storage/products/EPONGE-POUR-AQUARIUM-trixie-300x300.jpg',
            ],
            [
                'category_id' => 4, 'subcategory_id' => 14,
                'name' => 'Perles de Verre Lapis Lazuli Aquarium',
                'slug' => 'perles-de-verre-lapis-lazuli-aquarium',
                'description' => 'Décoration aquarium en perles de verre colorées Lapis Lazuli. Couleur bleue intense naturelle, inoffensif pour les poissons.',
                'short_description' => 'Perles décoratives bleues pour aquarium',
                'price' => 35.00, 'price_old' => 45.00, 'stock' => 50,
                'sku' => 'PERLES-LAPIS-AQU', 'is_active' => true,
                'is_new' => true,
                'discount_percentage' => 22, 'rating' => 4.5, 'review_count' => 39,
                'image' => 'storage/products/Perles-de-Verre-Lapi-Lazuli--300x300.jpg',
            ],

            // =============================================
            // PIGEONS (category_id: 5)
            // =============================================

            // --- Cages & Volières (subcategory_id: 16) ---
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Cage Élevage Zolux Primo Cati 671 Pigeons',
                'slug' => 'cage-elevage-zolux-primo-cati-671-pigeons',
                'description' => 'Cage d\'élevage Zolux pour pigeons et tourterelles. Structure robuste avec barreaux espacés adaptés. Accessoires inclus.',
                'short_description' => 'Cage d\'élevage robuste pour pigeons',
                'price' => 290.00, 'price_old' => 340.00, 'stock' => 12,
                'sku' => 'ZOLUX-CATI-671-PIG', 'is_active' => true,
                'discount_percentage' => 15, 'rating' => 4.5, 'review_count' => 19,
                'image' => 'storage/products/Cage-delevage-Zolux-Primo-cati-671-300x300.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Abreuvoir Mangeoire Pigeons 8L Bleu GAUN',
                'slug' => 'abreuvoir-mangeoire-pigeons-8l-bleu-gaun',
                'description' => 'Abreuvoir-mangeoire combiné GAUN pour pigeons. Grande capacité 8L pour un approvisionnement continu. Facile à entretenir.',
                'short_description' => 'Abreuvoir-mangeoire combiné 8L pour pigeons',
                'price' => 110.00, 'price_old' => 130.00, 'stock' => 30,
                'sku' => 'GAUN-ABREUVOIR-8L', 'is_active' => true,
                'discount_percentage' => 15, 'rating' => 4.6, 'review_count' => 41,
                'image' => 'storage/products/abreuvoir-mangeoire-pour-pigeons-8-l-bleu-gaun-1295-eur-30102-gaun-abreuvoir-mangeoire-pour-pigeons-8-l-bleu-gaun.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Mangeoire Pigeons Qubus 80cm Demster',
                'slug' => 'mangeoire-pigeons-qubus-80cm-demster',
                'description' => 'Mangeoire longue Qubus 80cm pour pigeons en volière. Accès facile pour plusieurs oiseaux simultanément.',
                'short_description' => 'Mangeoire collective 80cm pour volière',
                'price' => 75.00, 'price_old' => null, 'stock' => 25,
                'sku' => 'MANGEOIRE-QUBUS-80CM', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.4, 'review_count' => 17,
                'image' => 'storage/products/mangeoire-pigeons-qubus-80-cm-demster.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Panier Entraînement Aluminium MIRA 110x28x61cm',
                'slug' => 'panier-entrainement-aluminium-mira-110x28x61cm',
                'description' => 'Panier d\'entraînement en aluminium MIRA pour pigeons voyageurs. Robuste et léger, idéal pour les lâchers d\'entraînement.',
                'short_description' => 'Panier entraînement aluminium pour pigeons voyageurs',
                'price' => 580.00, 'price_old' => 650.00, 'stock' => 8,
                'sku' => 'MIRA-BASKET-ALUM', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 11, 'rating' => 4.8, 'review_count' => 14,
                'image' => 'storage/products/panier-d-entrainement-en-aluminium-mira-110x28x61-cm-demster.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Panier Entraînement Bois Limoges 89.90x26x46cm',
                'slug' => 'panier-entrainement-bois-limoges-89x26x46cm',
                'description' => 'Panier d\'entraînement en bois naturel pour pigeons voyageurs. Style traditionnel Limoges, solide et durable.',
                'short_description' => 'Panier entraînement en bois naturel',
                'price' => 380.00, 'price_old' => 440.00, 'stock' => 10,
                'sku' => 'LIMOGES-BASKET-WOOD', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.6, 'review_count' => 11,
                'image' => 'storage/products/panier-d-entrainement-pour-pigeon-en-bois-limoges-89-90x26x46cm-demster.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Panier Exposition Petit Natural',
                'slug' => 'panier-exposition-petit-natural',
                'description' => 'Panier d\'exposition compact pour pigeons de concours. Finition naturelle élégante, idéal pour les expositions et jugements.',
                'short_description' => 'Panier exposition compact pour concours',
                'price' => 120.00, 'price_old' => null, 'stock' => 20,
                'sku' => 'PANIER-EXPO-NAT', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.5, 'review_count' => 8,
                'image' => 'storage/products/panier-d-exposition-petit-natural-2.jpg',
            ],

            // --- Graines & Nutrition (subcategory_id: 15) ---
            [
                'category_id' => 5, 'subcategory_id' => 15,
                'name' => 'Enzymix 7.50 MS Mue Méthionine 20kg Beyers',
                'slug' => 'enzymix-750-ms-mue-methionine-20kg-beyers',
                'description' => 'Mélange de mue haute qualité Beyers pour pigeons. Enrichi en méthionine pour favoriser une mue rapide et un beau plumage.',
                'short_description' => 'Mélange mue haute qualité 20kg - Beyers',
                'price' => 220.00, 'price_old' => 260.00, 'stock' => 25,
                'sku' => 'BEYERS-ENZYMIX-20KG', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 15, 'rating' => 4.8, 'review_count' => 42,
                'image' => 'storage/products/enzymix-7-50-ms-mue-methionine-20kg-beyers-2270-eur-070050-beyers-enzymix-7-50-ms-mue-methionine-20-kg-melange-de-mue-haute-qual.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 15,
                'name' => 'Mélanges Premium Pigeons',
                'slug' => 'melanges-premium-pigeons',
                'description' => 'Mélange de céréales premium pour pigeons de sport et d\'élevage. Composition équilibrée pour maintenir les performances.',
                'short_description' => 'Mélange premium sport & élevage pigeons',
                'price' => 85.00, 'price_old' => 100.00, 'stock' => 45,
                'sku' => 'MELANGES-PREMIUM-PIG', 'is_active' => true,
                'is_bestseller' => true,
                'discount_percentage' => 15, 'rating' => 4.7, 'review_count' => 78,
                'image' => 'storage/products/melanges-premium.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 15,
                'name' => 'Grit 20kg Beyers Plus - Minéraux pour Pigeons',
                'slug' => 'grit-20kg-beyers-plus-mineraux-pigeons',
                'description' => 'Mélange de minéraux Beyers Plus composé de grit, coquillages et huître. Essentiel pour la digestion et la solidité des œufs.',
                'short_description' => 'Mélange minéraux grit & coquillages 20kg',
                'price' => 150.00, 'price_old' => 175.00, 'stock' => 30,
                'sku' => 'GRIT-BEYERS-20KG', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.6, 'review_count' => 35,
                'image' => 'storage/products/grit-20kg-beyers-plus-003622-beyers-plus-un-melange-de-mineraux-compose-de-grit-de-coquillage-de-grit-de-coquille-dhuitre-de-gra-_1.webp',
            ],

            // --- Accessoires (subcategory_id: 17) ---
            [
                'category_id' => 5, 'subcategory_id' => 17,
                'name' => 'Colombine Vita 4kg - Vitamines & Minéraux Pigeons',
                'slug' => 'colombine-vita-4kg-vitamines-mineraux-pigeons',
                'description' => 'Complément vitaminé en poudre Colombine Vita pour pigeons. Vitamines, oligo-éléments et minéraux essentiels à la reproduction.',
                'short_description' => 'Complément vitamines & minéraux en poudre 4kg',
                'price' => 160.00, 'price_old' => 190.00, 'stock' => 22,
                'sku' => 'COLOMBINE-VITA-4KG', 'is_active' => true,
                'discount_percentage' => 16, 'rating' => 4.7, 'review_count' => 48,
                'image' => 'storage/products/colombine-vita-4kg-vitamines-oligo-elements-et-mineraux-en-poudre-1560-eur-412361-versele-laga-vitamines-oligoelements-et-minera.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Bactair Spray Hygiène Pigeons',
                'slug' => 'bactair-spray-hygiene-pigeons',
                'description' => 'Spray désinfectant Bactair pour colombiers et cages. Élimine les bactéries et agents pathogènes. Application facile en spray.',
                'short_description' => 'Spray désinfectant pour colombiers',
                'price' => 95.00, 'price_old' => 110.00, 'stock' => 35,
                'sku' => 'BACTAIR-SPRAY', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.5, 'review_count' => 27,
                'image' => 'storage/products/bactair-spray.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 17,
                'name' => 'BetaChol 1L - Vitamine E & Sélénium Pigeons',
                'slug' => 'betachol-1l-vitamine-e-selenium-pigeons',
                'description' => 'Concentré en vitamine E et sélénium Rohnfried pour pigeons. Améliore la fertilité, la vitalité et les performances en vol.',
                'short_description' => 'Vitamine E & Sélénium pour pigeons 1L',
                'price' => 185.00, 'price_old' => 215.00, 'stock' => 18,
                'sku' => 'BETACHOL-1L', 'is_active' => true,
                'is_featured' => true,
                'discount_percentage' => 14, 'rating' => 4.8, 'review_count' => 33,
                'image' => 'storage/products/betachol-1l.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 17,
                'name' => 'Taubenfit E50 Vitamine E Rohnfried 100ml',
                'slug' => 'taubenfit-e50-vitamine-e-rohnfried-100ml',
                'description' => 'Concentré Vitamine E Taubenfit pour pigeons d\'élevage et de vol. Améliore les résultats de reproduction et la résistance.',
                'short_description' => 'Concentré Vitamine E pour pigeons 100ml',
                'price' => 95.00, 'price_old' => 110.00, 'stock' => 28,
                'sku' => 'TAUBENFIT-E50-100ML', 'is_active' => true,
                'discount_percentage' => 14, 'rating' => 4.7, 'review_count' => 22,
                'image' => 'storage/products/taubenfit-e-50-vit-e-konzentrat-vit-e-et-selenium-la-periode-d-elevage-et-de-vol-100ml-rohnfried.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Bagues Élastiques E-Z par 50 pièces 8mm Jaune',
                'slug' => 'bagues-elastiques-ez-50-pieces-8mm-jaune',
                'description' => 'Bagues d\'identification colorées E-Z pour pigeons. Lot de 50 bagues élastiques de 8mm de couleur jaune, faciles à poser.',
                'short_description' => 'Lot 50 bagues d\'identification jaunes 8mm',
                'price' => 35.00, 'price_old' => null, 'stock' => 60,
                'sku' => 'BAGUES-EZ-50-JAUNE-8MM', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.3, 'review_count' => 26,
                'image' => 'storage/products/bagues-elastiques-e-z-par-50-pieces-taille-8-mm-couleur-jaune-650-eur-880err08-yellow-rings-4-wings-voila-une-nouvelle-conceptio.jpg',
            ],
            [
                'category_id' => 5, 'subcategory_id' => 16,
                'name' => 'Grattoir 16cm Manche Vert Ornibird',
                'slug' => 'grattoir-16cm-manche-vert-ornibird',
                'description' => 'Grattoir Ornibird 16cm avec manche vert en plastique. Outil pratique pour le nettoyage des fientes dans les cages et colombiers.',
                'short_description' => 'Grattoir de nettoyage 16cm pour colombiers',
                'price' => 18.00, 'price_old' => null, 'stock' => 80,
                'sku' => 'GRATTOIR-ORNIBIRD-16CM', 'is_active' => true,
                'discount_percentage' => 0, 'rating' => 4.2, 'review_count' => 15,
                'image' => 'storage/products/grattoir-16cm-manche-vert-en-plastique-475-eur-26028-private-label-ornibird-grattoir-16cm-manche-vert-en-plastique-permet-de-net.jpg',
            ],
        ];

        foreach ($products as $product) {
            \App\Models\Product::updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}
